module.exports.ASCII_LETTERS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
module.exports.ASCII_LOWER = "abcdefghijklmnopqrstuvwxyz"
module.exports.ASCII_UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
module.exports.PUNCTUATION = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
module.exports.DIGITS = "0123456789"
module.exports.WHITESPACE = " \t\n\r\x0b\x0c"
